#!/bin/sh

# user@hostname
# OS:        Linux
# KERNEL:    Linux 6.9
# UPTIME:    4 hours, 20 minutes
# PACKAGES:  666
# SHELL:     sh
# WM:        wm
# TERMINAL:  tty

# File:         fetch
# Description:  Fetch template to customize
# Author:       NNB
#               └─ https://github.com/NNBnh
# URL:          https://github.com/NNBnh/textart-collections/blob/main/fetch


# Values
OS=$(lsb_release -sd | sed 's/"//g')
KERNEL=$(uname -sr)
UPTIME=$(uptime -p | sed 's/up //')
PACKAGES=$PACKAGES
SHELL=$(basename "$SHELL")
WM=$WM
TERMINAL=$(basename "$TERMINAL")


# Start
printf "\e[1;97m${USER}\e[0m@\e[1;97m$(hostname)\e[0m
\e[1;97mOS:        \e[0m${OS:-os}\e[0m
\e[1;97mKERNEL:    \e[0m${KERNEL:-kernel}\e[0m
\e[1;97mUPTIME:    \e[0m${UPTIME:-uptime}\e[0m
\e[1;97mPACKAGES:  \e[0m${PACKAGES:-packages}\e[0m
\e[1;97mSHELL:     \e[0m${SHELL:-shell}\e[0m
\e[1;97mWM:        \e[0m${WM:-wm}\e[0m
\e[1;97mTERMINAL:  \e[0m${TERMINAL:-terminal}\e[0m"


exit 0
