#!/bin/sh

# ┌───┐
# │▐█▌│
# │+ ⠔│
# └───'
#GameBtw

# File:         gamebtw
# Description:  Game-boy + Arch-Btw = Game Btw
# Author:       NNB
#               └─ https://github.com/NNBnh
# URL:          https://github.com/NNBnh/nnbs-text-art/blob/main/gamebtw


# Start
printf " \033[90m┌───┐\033[0m
 \033[90m│\033[93m▐█▌\033[90m│\033[0m
 \033[90m│\033[1m+ \033[91m⠔\033[0;90m│\033[0m
 \033[90m└───'\033[0m
\033[1;93mGameBtw\033[0m"


exit 0
