#!/bin/sh

# ┌───┐
# │▐█▌│
# │+ ⠔│
# └───'
#GameBtw

# File:         gamebtw
# Description:  Game-boy + Arch-Btw = Game Btw
# Author:       NNB
#               └─ https://github.com/NNBnh
# URL:          https://github.com/NNBnh/nnbs-text-art/blob/main/gamebtw


# Start
printf " \e[37m┌───┐\e[0m
 \e[37m│\e[93m▐█▌\e[37m│\e[0m
 \e[37m│\e[1m+ \e[91m⠔\e[0;37m│\e[0m
 \e[37m└───'\e[0m
\e[1;93mGameBtw\e[0m"


exit 0
